server:
   port: 9000
        
spring:
   jmx:
      enabled: true
      default_domain: Kafdrop
   jackson:
      deserialization:
         fail_on_unknown_properties: false
         read_unknown_enum_values_as_null: true

endpoints.jmx.domain: ${spring.jmx.default_domain}
metrics.jmx.domain: ${spring.jmx.default_domain}-metrics
management.contextPath: /debug

kafdrop.monitor:
   kafkaVersion: "0.11.0.2"
   threadPoolSize: 10
   retry:
      maxAttempts: 3
      backoffMillis: 1000


curator.discovery:
   enabled: true
   basePath: /homeadvisor/services

# Properties to expose via the InfoEndpoint & ServiceDiscovery
info.build:
   artifact: ${project.artifactId}
   name: ${project.name}
   description: ${project.description}
   version: ${project.version}

# Default values usually provided by Maven during a build
project:
   artifactId: ${project.artifactId}
   name: ${project.name}
   description: ${project.description}
   version: ${project.version}
            
logging:
    level:
        ROOT: INFO
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} LEVEL: %6.6level --- [%20.20t] %-40.40logger{0} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} LEVEL: %6.6level --- [%20.20t] %-40.40logger{0} - %msg%n"
    file: logs/kafdrop.log
logging.file:
    max-history: 5
    max-size: 50MB