kafka:
    consumer:
        threads: 1
        groupId: Kafdrop
        pollTimeout: 6000
        pollMaxRecords: 100
        sessionTimeout: 10000
        resumeTime: 600000
        consumerErrorsTopic: ConsumerErrors
    producer:
        timeout: 1000
    connect: 
        
spring:
   jmx:
      enabled: true
      default_domain: Kafdrop
   jackson:
      deserialization:
         fail_on_unknown_properties: false
         read_unknown_enum_values_as_null: true

management:
  security.enabled: false
  contextPath: /actuator
  metrics:
    useGlobalRegistry: false

endpoints.jmx.domain: ${spring.jmx.default_domain}
metrics.jmx.domain: ${spring.jmx.default_domain}-metrics

kafdrop.monitor:
   kafkaVersion: "0.11.0.2"
   threadPoolSize: 10
   retry:
      maxAttempts: 3
      backoffMillis: 1000


curator.discovery:
   enabled: true
   basePath: /homeadvisor/services

# Properties to expose via the InfoEndpoint & ServiceDiscovery
info.build:
   artifact: ${project.artifactId}
   name: ${project.name}
   description: ${project.description}
   version: ${project.version}

# Default values usually provided by Maven during a build
project:
   artifactId: ${project.artifactId}
   name: ${project.name}
   description: ${project.description}
   version: ${project.version}
            
logging:
    level:
        ROOT: INFO
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} LEVEL: %6.6level --- [%20.20t] %-40.40logger{0} - %msg%n%ex%n"